apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpclient
  namespace: default
  labels:
    purpose: generate-http-load
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kubeturbo.io/monitored: "false"
      labels:
        app: httpclient
    spec:
      serviceAccount: default
      containers:
        - name: httpclient
          image: beekman9527/webclient:v1
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --threadNum=10
            - --target=http://10.3.0.160:8080/cpuwork.php/?cpu=20
            - --rps=2
